[package]
name = "sath"
description = "Toy math library"
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["ItsEthra"]
repository = "https://github.com/ItsEthra/sath"

[dependencies]
bytemuck = { version = "1", optional = true }
