[package]
name = "sath"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["ItsEthra"]
repository = "https://github.com/ItsEthra/sath"

[features]
use-f64 = []

[dependencies]
bytemuck = "1.13"
